<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.3-1.el10_2 setup script
 * Date: Tue, 18 Nov 2025 04:50:01 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: www [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'www';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'webmaster';
$cfg['Servers'][$i]['password'] = 'W3b@Ci45t@D8';

/* End of servers configuration */

$cfg['blowfish_secret'] = \sodium_hex2bin('37b70d9feb9e40f0d5c21b6d2511c518f62eacf5bc75967ff2d5be5e83ae96d9');
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
